# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe09d0fc018232a5319dd185e9eb39206ba56899ee8aa4adddf65abc1061c0f7e2dd92d13a29603ce0deb30e5c0a53c5e952b197d6a2ca5de37e89872236568a

test:
  secret_key_base: 8217514566d141b8fcf7f5f4f9b0fb7b34551a6a7b349f1ff3a1f406a92df90fbeee40b2bd3ebf0864d26ae8c9be8e9fafed2df38b7422f6290478c8b812efc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
